version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5430:5432"
    restart: always
    environment:
      POSTGRES_DB: quarkus_demo
      POSTGRES_USER: quarkus_demo
      POSTGRES_PASSWORD: pHvyWGTNesusAU4S
